### PR TITLE
Introduced updater module and code cleanup

### PR DESCRIPTION
**Pull request by HitaloSama**
I did a general cleaning of the code using PyCharm and adapted the [Watzon's tg_userbot updater module](https://github.com/watzon/tg_userbot).

NOTE: Unlike PR #4 you can define the variable UPSTREAM_REPO_URL if you use a fork and other corrections were also made.

### CODE REVIEW

**Comment by nunopenim** [comment]
`GBANS = False
    GBAN_BOTS = None
    AUTOMATION_ENABLED = False
    AUTOMATION_SENDERS = []  # IDs
    AUTOMATION_COMMANDS = []  # strings
    AUTOMATION_TRIGGERS = []  # strings
    Q_API_TOKEN = None  # Quotly API key http://antiddos.systems
    OPEN_WEATHER_MAP_APPID = None  # OWM API key https://openweathermap.org/
    OPEN_WEATHER_MAP_DEFCITY = None  # default city to be used for weather
    UPSTREAM_REPO_URL = "https://github.com/nunopenim/tguserbot.git"  # Custom (forked) repo URL for updater.
    GBANS = ""
    GBAN_BOT = ""`

In config.py, why there is GBANS both as boolean and string, and GBAN_BOTS as an array (I assume) and as a string?

**Comment by nunopenim** [comment]
in sample_config.py, on lines 38, 39, 48 and 49, why are multiple GBAN and GBAN bots? Also, why is type of 48 and 49 a String?

**Comment by HitaloSama** [comment]
@nunopenim fixed :joy:

**Comment by nunopenim** [comment]
Alright, it needs correction here and there, specially in the new added module, but it seems okay.

**Pull request merged**
